### PR TITLE
Cleanning the reference of kmeds and KMeds issue #42

### PR DESCRIPTION
**Pull request by dhaval737**

### CODE REVIEW

**Review by motiwari — CHANGES_REQUESTED** [review]
Apologies for the late review here, @dhaval737 .

Could you describe how you made these changes? Did you use `codemod`, `sed`? Or, even better, re-generate via Doxygen? If so, what was the command?

Additionally, could you describe how you tested that this PR doesn't break anything? There are some testing instructions in the `README`; let me know if you need help testing

**Comment by motiwari** [comment]
By the way, Github requires a few specific strings to close the issue automatically and tie the issue to code -- could you change the PR message to "Fixes #42" or one of the other such strings?

**Comment by dhaval737** [comment]
> Apologies for the late review here, @dhaval737 .
> 
> Could you describe how you made these changes? Did you use `codemod`, `sed`? Or, even better, re-generate via Doxygen? If so, what was the command?
> 
> Additionally, could you describe how you tested that this PR doesn't break anything? There are some testing instructions in the `README`; let me know if you need help testing

No, I did not test it. I will read the instructions from the README and test it to make sure it has not broken anything.

**Comment by dhaval737** [comment]
> Apologies for the late review here, @dhaval737 .
> 
> Could you describe how you made these changes? Did you use `codemod`, `sed`? Or, even better, re-generate via Doxygen? If so, what was the command?
> 
> Additionally, could you describe how you tested that this PR doesn't break anything? There are some testing instructions in the `README`; let me know if you need help testing

Answer to your first point I did manually search for the string in each file and replace the string.

**Comment by motiwari** [comment]
@dhaval737 looks like you created a new PR, a duplicate of https://github.com/ThrunGroup/BanditPAM/pull/66. Which is the one we should be looking at? Can you close one of them?

**Comment by motiwari** [comment]
Closing as fixed in #66

**Pull request closed without merging**
